drop table if exists personnes; 
create table PERSONNES (
    ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    VERSION integer not null,
    NOM varchar(30) not null,
    PRENOM varchar(30) not null,
    CIVILITE integer  not null,
    CREATED timestamp  not null,
    MODIFIED timestamp,
    CONSTRAINT IDX_PERSONNES PRIMARY KEY (ID)
);

INSERT INTO PERSONNES ( ID, VERSION, NOM, PRENOM, CIVILITE, CREATED, MODIFIED) VALUES (1, 1, 'MARTIN', 'Jules', 1, now(),null);
INSERT INTO PERSONNES ( ID, VERSION, NOM, PRENOM, CIVILITE, CREATED, MODIFIED) VALUES (2, 1, 'GERMAN', 'Christine', 2, now(),null);
INSERT INTO PERSONNES ( ID, VERSION, NOM, PRENOM, CIVILITE, CREATED, MODIFIED) VALUES (3, 1, 'JACQUARD', 'Jules', 1, now(),null);
INSERT INTO PERSONNES ( ID, VERSION, NOM, PRENOM, CIVILITE, CREATED, MODIFIED) VALUES (4, 1, 'BISTROU', 'Brigitte', 3, now(),null);


drop table if exists Adresses;
CREATE TABLE ADRESSES (
    ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    VERSION integer not null,
    ADR1 varchar(32) not null,
    ADR2 varchar(32),
    VILLE varchar(32) not null,
    CP varchar(5) not null,
	CREATED timestamp   not null,
    CONSTRAINT IDX_ADRESSES PRIMARY KEY (ID)
);
INSERT INTO ADRESSES ( ID, VERSION, ADR1, ADR2, VILLE, CP, CREATED) VALUES (1,1, 'rue de la broche',null,'Niort', '79000', now());
INSERT INTO ADRESSES ( ID, VERSION, ADR1, ADR2, VILLE, CP, CREATED) VALUES (2,1, 'rue de la barre',null,'Niort', '79001', now());
INSERT INTO ADRESSES ( ID, VERSION, ADR1, ADR2, VILLE, CP, CREATED) VALUES (3,1, 'rue de la pioche',null,'Niort', '79002', now());

drop table if exists civilites;
CREATE TABLE CIVILITES ( 
	ID integer NOT NULL, 
    LIBELLE_COURT varchar(5) not null,
    LIBELLE_LONG varchar(30) not null,
    CONSTRAINT IDX_CIVILITES PRIMARY KEY (ID)
);
INSERT INTO CIVILITES ( ID, LIBELLE_COURT, LIBELLE_LONG) VALUES (1, 'Mr.', 'Monsieur');
INSERT INTO CIVILITES ( ID, LIBELLE_COURT, LIBELLE_LONG) VALUES (2, 'Mme.', 'Madame');
INSERT INTO CIVILITES ( ID, LIBELLE_COURT, LIBELLE_LONG) VALUES (3, 'Mlle.', 'Mademoiselle');

drop table if exists personne_adresse;
CREATE TABLE PERSONNE_ADRESSE ( 
	personneId bigint NOT NULL, 
	adresseId bigint NOT NULL, 
	PRIMARY KEY (personneId,adresseId)
);
INSERT INTO PERSONNE_ADRESSE (personneId, adresseId) values (1,1);
INSERT INTO PERSONNE_ADRESSE (personneId, adresseId) values (1,2);
INSERT INTO PERSONNE_ADRESSE (personneId, adresseId) values (2,1);
INSERT INTO PERSONNE_ADRESSE (personneId, adresseId) values (2,3);
INSERT INTO PERSONNE_ADRESSE (personneId, adresseId) values (4,2);

DROP TABLE IF EXISTS TELEPHONES;
create table TELEPHONES (
    ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    VERSION integer not null,
    OWNER_ID bigint not null,
	TELEPHONE_TYPE  varchar(8) not null,
	NUMERO  varchar(10),
    CONSTRAINT IDX_TELEPHONES PRIMARY KEY (ID)
);
insert into TELEPHONES (id, version, owner_id, telephone_type, numero) values (1,1,1,'bureau','0101030405');
insert into TELEPHONES (id, version, owner_id, telephone_type, numero) values (2,1,1,'mobile','0102030405');
insert into TELEPHONES (id, version, owner_id, telephone_type, numero) values (3,1,2,'bureau','0103030405');

alter table telephones add 
	    CONSTRAINT FK_PERSONNE FOREIGN KEY (OWNER_ID) REFERENCES PERSONNES (ID);